spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wansenerp?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: passw0rd
    dynamic:
      druid:
        max-wait: 60000
        initial-size: 5
        min-idle: 5
        max-active: 20