[package]
name = "airpi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.33.0"
tensorflow = { version = "0.21.0", features = ["tensorflow_gpu"] }